# coding: utf-8

"""
    QAN AutoApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qan.qan.output_get_block_transaction_count_by_hash import OutputGetBlockTransactionCountByHash

class TestOutputGetBlockTransactionCountByHash(unittest.TestCase):
    """OutputGetBlockTransactionCountByHash unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OutputGetBlockTransactionCountByHash:
        """Test OutputGetBlockTransactionCountByHash
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OutputGetBlockTransactionCountByHash`
        """
        model = OutputGetBlockTransactionCountByHash()
        if include_optional:
            return OutputGetBlockTransactionCountByHash(
                var_schema = '',
                transaction_count = ''
            )
        else:
            return OutputGetBlockTransactionCountByHash(
                transaction_count = '',
        )
        """

    def testOutputGetBlockTransactionCountByHash(self):
        """Test OutputGetBlockTransactionCountByHash"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
