# coding: utf-8

"""
    QAN AutoApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_qan_accounts(self) -> None:
        """Test case for qan_accounts

        """
        pass

    def test_qan_blob_base_fee(self) -> None:
        """Test case for qan_blob_base_fee

        """
        pass

    def test_qan_block_number(self) -> None:
        """Test case for qan_block_number

        """
        pass

    def test_qan_call(self) -> None:
        """Test case for qan_call

        """
        pass

    def test_qan_chain_id(self) -> None:
        """Test case for qan_chain_id

        """
        pass

    def test_qan_estimate_gas(self) -> None:
        """Test case for qan_estimate_gas

        """
        pass

    def test_qan_fee_history(self) -> None:
        """Test case for qan_fee_history

        """
        pass

    def test_qan_gas_price(self) -> None:
        """Test case for qan_gas_price

        """
        pass

    def test_qan_get_account(self) -> None:
        """Test case for qan_get_account

        """
        pass

    def test_qan_get_balance(self) -> None:
        """Test case for qan_get_balance

        """
        pass

    def test_qan_get_block_by_hash(self) -> None:
        """Test case for qan_get_block_by_hash

        """
        pass

    def test_qan_get_block_by_number(self) -> None:
        """Test case for qan_get_block_by_number

        """
        pass

    def test_qan_get_block_receipts(self) -> None:
        """Test case for qan_get_block_receipts

        """
        pass

    def test_qan_get_block_transaction_count_by_hash(self) -> None:
        """Test case for qan_get_block_transaction_count_by_hash

        """
        pass

    def test_qan_get_block_transaction_count_by_number(self) -> None:
        """Test case for qan_get_block_transaction_count_by_number

        """
        pass

    def test_qan_get_code(self) -> None:
        """Test case for qan_get_code

        """
        pass

    def test_qan_get_filter_changes(self) -> None:
        """Test case for qan_get_filter_changes

        """
        pass

    def test_qan_get_filter_logs(self) -> None:
        """Test case for qan_get_filter_logs

        """
        pass

    def test_qan_get_logs(self) -> None:
        """Test case for qan_get_logs

        """
        pass

    def test_qan_get_proof(self) -> None:
        """Test case for qan_get_proof

        """
        pass

    def test_qan_get_storage_at(self) -> None:
        """Test case for qan_get_storage_at

        """
        pass

    def test_qan_get_transaction_by_block_hash_and_index(self) -> None:
        """Test case for qan_get_transaction_by_block_hash_and_index

        """
        pass

    def test_qan_get_transaction_by_block_number_and_index(self) -> None:
        """Test case for qan_get_transaction_by_block_number_and_index

        """
        pass

    def test_qan_get_transaction_by_hash(self) -> None:
        """Test case for qan_get_transaction_by_hash

        """
        pass

    def test_qan_get_transaction_count(self) -> None:
        """Test case for qan_get_transaction_count

        """
        pass

    def test_qan_get_transaction_receipt(self) -> None:
        """Test case for qan_get_transaction_receipt

        """
        pass

    def test_qan_get_uncle_count_by_block_hash(self) -> None:
        """Test case for qan_get_uncle_count_by_block_hash

        """
        pass

    def test_qan_get_uncle_count_by_block_number(self) -> None:
        """Test case for qan_get_uncle_count_by_block_number

        """
        pass

    def test_qan_max_priority_fee_per_gas(self) -> None:
        """Test case for qan_max_priority_fee_per_gas

        """
        pass

    def test_qan_new_block_filter(self) -> None:
        """Test case for qan_new_block_filter

        """
        pass

    def test_qan_new_filter(self) -> None:
        """Test case for qan_new_filter

        """
        pass

    def test_qan_new_pending_transaction_filter(self) -> None:
        """Test case for qan_new_pending_transaction_filter

        """
        pass

    def test_qan_send_raw_transaction(self) -> None:
        """Test case for qan_send_raw_transaction

        """
        pass

    def test_qan_subscribe(self) -> None:
        """Test case for qan_subscribe

        """
        pass

    def test_qan_syncing(self) -> None:
        """Test case for qan_syncing

        """
        pass

    def test_qan_uninstall_filter(self) -> None:
        """Test case for qan_uninstall_filter

        """
        pass

    def test_qan_unsubscribe(self) -> None:
        """Test case for qan_unsubscribe

        """
        pass

    def test_qan_xlink_valid(self) -> None:
        """Test case for qan_xlink_valid

        """
        pass


if __name__ == '__main__':
    unittest.main()
