# coding: utf-8

"""
    QAN AutoApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qan.qan.output_chain_id import OutputChainId

class TestOutputChainId(unittest.TestCase):
    """OutputChainId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OutputChainId:
        """Test OutputChainId
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OutputChainId`
        """
        model = OutputChainId()
        if include_optional:
            return OutputChainId(
                var_schema = '',
                chain_id = ''
            )
        else:
            return OutputChainId(
                chain_id = '',
        )
        """

    def testOutputChainId(self):
        """Test OutputChainId"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
