# coding: utf-8

"""
    QAN AutoApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qan.qan.input_fee_history import InputFeeHistory

class TestInputFeeHistory(unittest.TestCase):
    """InputFeeHistory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InputFeeHistory:
        """Test InputFeeHistory
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InputFeeHistory`
        """
        model = InputFeeHistory()
        if include_optional:
            return InputFeeHistory(
                var_schema = '',
                block_count = 56,
                newest_block = 'latest',
                reward_percentiles = [
                    0
                    ]
            )
        else:
            return InputFeeHistory(
                block_count = 56,
                newest_block = 'latest',
                reward_percentiles = [
                    0
                    ],
        )
        """

    def testInputFeeHistory(self):
        """Test InputFeeHistory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
