# coding: utf-8

"""
    QAN AutoApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.output_get_account import OutputGetAccount

class TestOutputGetAccount(unittest.TestCase):
    """OutputGetAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OutputGetAccount:
        """Test OutputGetAccount
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OutputGetAccount`
        """
        model = OutputGetAccount()
        if include_optional:
            return OutputGetAccount(
                var_schema = '',
                balance = '',
                code_hash = '',
                nonce = '',
                storage_root = ''
            )
        else:
            return OutputGetAccount(
                balance = '',
                code_hash = '',
                nonce = '',
                storage_root = '',
        )
        """

    def testOutputGetAccount(self):
        """Test OutputGetAccount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
