# coding: utf-8

"""
    QAN AutoApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qan.qan.output_max_priority_fee_per_gas import OutputMaxPriorityFeePerGas

class TestOutputMaxPriorityFeePerGas(unittest.TestCase):
    """OutputMaxPriorityFeePerGas unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OutputMaxPriorityFeePerGas:
        """Test OutputMaxPriorityFeePerGas
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OutputMaxPriorityFeePerGas`
        """
        model = OutputMaxPriorityFeePerGas()
        if include_optional:
            return OutputMaxPriorityFeePerGas(
                var_schema = '',
                max_priority_fee_per_gas = ''
            )
        else:
            return OutputMaxPriorityFeePerGas(
                max_priority_fee_per_gas = '',
        )
        """

    def testOutputMaxPriorityFeePerGas(self):
        """Test OutputMaxPriorityFeePerGas"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
