# coding: utf-8

"""
    QAN AutoApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qan.qan.output_get_proof import OutputGetProof

class TestOutputGetProof(unittest.TestCase):
    """OutputGetProof unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OutputGetProof:
        """Test OutputGetProof
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OutputGetProof`
        """
        model = OutputGetProof()
        if include_optional:
            return OutputGetProof(
                var_schema = '',
                account_proof = '',
                address = '',
                balance = '',
                code_hash = '',
                nonce = '',
                storage_hash = '',
                storage_proof = [
                    qan.models.response_storage_entry.Response_StorageEntry(
                        key = '', 
                        proof = '', 
                        value = '', )
                    ]
            )
        else:
            return OutputGetProof(
                account_proof = '',
                address = '',
                balance = '',
                code_hash = '',
                nonce = '',
                storage_hash = '',
                storage_proof = [
                    qan.models.response_storage_entry.Response_StorageEntry(
                        key = '', 
                        proof = '', 
                        value = '', )
                    ],
        )
        """

    def testOutputGetProof(self):
        """Test OutputGetProof"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
