# coding: utf-8

"""
    QAN AutoApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qan.qan.input_estimate_gas import InputEstimateGas

class TestInputEstimateGas(unittest.TestCase):
    """InputEstimateGas unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InputEstimateGas:
        """Test InputEstimateGas
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InputEstimateGas`
        """
        model = InputEstimateGas()
        if include_optional:
            return InputEstimateGas(
                var_schema = '',
                object = qan.models.estimate_gas_object.EstimateGasObject(
                    balance = '', 
                    code = 56, 
                    nonce = '', 
                    state = '', 
                    state_diff = '', ),
                transaction = qan.models.params_transaction.Params_Transaction(
                    data = '', 
                    from = '', 
                    gas = '', 
                    gas_price = '', 
                    to = '', 
                    value = '', )
            )
        else:
            return InputEstimateGas(
                transaction = qan.models.params_transaction.Params_Transaction(
                    data = '', 
                    from = '', 
                    gas = '', 
                    gas_price = '', 
                    to = '', 
                    value = '', ),
        )
        """

    def testInputEstimateGas(self):
        """Test InputEstimateGas"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
