# coding: utf-8

"""
    QAN AutoApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qan.qan.output_get_transaction_by_block_number_and_index import OutputGetTransactionByBlockNumberAndIndex

class TestOutputGetTransactionByBlockNumberAndIndex(unittest.TestCase):
    """OutputGetTransactionByBlockNumberAndIndex unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OutputGetTransactionByBlockNumberAndIndex:
        """Test OutputGetTransactionByBlockNumberAndIndex
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OutputGetTransactionByBlockNumberAndIndex`
        """
        model = OutputGetTransactionByBlockNumberAndIndex()
        if include_optional:
            return OutputGetTransactionByBlockNumberAndIndex(
                var_schema = '',
                transaction = qan.models.response_transaction.Response_Transaction(
                    access_list = '', 
                    block_hash = '', 
                    block_number = '', 
                    chain_id = '', 
                    from = '', 
                    gas = '', 
                    gas_price = '', 
                    hash = '', 
                    input = '', 
                    max_fee_per_gas = '', 
                    max_priority_fee_per_gas = '', 
                    nonce = '', 
                    r = '', 
                    s = '', 
                    to = '', 
                    transaction_index = '', 
                    type = '', 
                    v = '', 
                    value = '', )
            )
        else:
            return OutputGetTransactionByBlockNumberAndIndex(
                transaction = qan.models.response_transaction.Response_Transaction(
                    access_list = '', 
                    block_hash = '', 
                    block_number = '', 
                    chain_id = '', 
                    from = '', 
                    gas = '', 
                    gas_price = '', 
                    hash = '', 
                    input = '', 
                    max_fee_per_gas = '', 
                    max_priority_fee_per_gas = '', 
                    nonce = '', 
                    r = '', 
                    s = '', 
                    to = '', 
                    transaction_index = '', 
                    type = '', 
                    v = '', 
                    value = '', ),
        )
        """

    def testOutputGetTransactionByBlockNumberAndIndex(self):
        """Test OutputGetTransactionByBlockNumberAndIndex"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
