# coding: utf-8

"""
    QAN AutoApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qan.qan.input_new_filter import InputNewFilter

class TestInputNewFilter(unittest.TestCase):
    """InputNewFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InputNewFilter:
        """Test InputNewFilter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InputNewFilter`
        """
        model = InputNewFilter()
        if include_optional:
            return InputNewFilter(
                var_schema = '',
                filter_object = qan.models.filter_object.FilterObject(
                    address = '', 
                    from_block = '', 
                    to_block = '', 
                    topics = [
                        ''
                        ], )
            )
        else:
            return InputNewFilter(
                filter_object = qan.models.filter_object.FilterObject(
                    address = '', 
                    from_block = '', 
                    to_block = '', 
                    topics = [
                        ''
                        ], ),
        )
        """

    def testInputNewFilter(self):
        """Test InputNewFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
