# coding: utf-8

"""
    QAN AutoApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.output_subscribe import OutputSubscribe

class TestOutputSubscribe(unittest.TestCase):
    """OutputSubscribe unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OutputSubscribe:
        """Test OutputSubscribe
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OutputSubscribe`
        """
        model = OutputSubscribe()
        if include_optional:
            return OutputSubscribe(
                var_schema = '',
                subscription_id = ''
            )
        else:
            return OutputSubscribe(
                subscription_id = '',
        )
        """

    def testOutputSubscribe(self):
        """Test OutputSubscribe"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
