# coding: utf-8

"""
    QAN AutoApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.output_unsubscribe import OutputUnsubscribe

class TestOutputUnsubscribe(unittest.TestCase):
    """OutputUnsubscribe unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OutputUnsubscribe:
        """Test OutputUnsubscribe
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OutputUnsubscribe`
        """
        model = OutputUnsubscribe()
        if include_optional:
            return OutputUnsubscribe(
                var_schema = '',
                result = True
            )
        else:
            return OutputUnsubscribe(
                result = True,
        )
        """

    def testOutputUnsubscribe(self):
        """Test OutputUnsubscribe"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
