# coding: utf-8

"""
    QAN AutoApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qan.qan.response_storage_entry import ResponseStorageEntry

class TestResponseStorageEntry(unittest.TestCase):
    """ResponseStorageEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseStorageEntry:
        """Test ResponseStorageEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseStorageEntry`
        """
        model = ResponseStorageEntry()
        if include_optional:
            return ResponseStorageEntry(
                key = '',
                proof = '',
                value = ''
            )
        else:
            return ResponseStorageEntry(
                key = '',
                proof = '',
                value = '',
        )
        """

    def testResponseStorageEntry(self):
        """Test ResponseStorageEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
