# coding: utf-8

"""
    QAN AutoApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ParamsTransaction(BaseModel):
    """
    ParamsTransaction
    """ # noqa: E501
    data: Optional[StrictStr] = Field(default=None, description="The hash of the method signature and encoded parameters. For more information, see the Contract ABI description in the Solidity documentation.", alias="Data")
    var_from: Optional[StrictStr] = Field(default=None, description="The address from which the transaction is sent", alias="From")
    gas: Optional[StrictStr] = Field(default=None, description="The integer of gas provided for the transaction execution", alias="Gas")
    gas_price: Optional[StrictStr] = Field(default=None, description="The integer of gasPrice used for each paid gas encoded as hexadecimal", alias="GasPrice")
    to: StrictStr = Field(description="The address to which the transaction is addressed", alias="To")
    value: Optional[StrictStr] = Field(default=None, description="The integer of value sent with this transaction encoded as hexadecimal", alias="Value")
    __properties: ClassVar[List[str]] = ["Data", "From", "Gas", "GasPrice", "To", "Value"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ParamsTransaction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ParamsTransaction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Data": obj.get("Data"),
            "From": obj.get("From"),
            "Gas": obj.get("Gas"),
            "GasPrice": obj.get("GasPrice"),
            "To": obj.get("To"),
            "Value": obj.get("Value")
        })
        return _obj


